### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by Mladen-Trampic-SRB-1989** [Mladen-Trampic-SRB-1989/SEBC#11]
- [x] Create the Issue `Install CDH`
- [x] Assign the issue to yourself and label it `started`
- [x] Install the CDH 5.9 release; deploy coreset services only
  - [x] Rename your cluster after your GitHub handle
- [x] Create user directories in HDFS for `ernest` and `siwicki`
- [x] Add the following to `3_cm.md`:
    - [x] Command and output for `hdfs dfs -ls /user`
    - [x] The output from the CM API call `../api/v14/hosts` 
- [x] Login to Hue and install the Hive sample data
    - [x] Capture the Hue home page to `challenges/labs/3_hue_installed.png`
- [x] Push this work to your GitHub repo and label the Issue `submitted`
- [x] Assign the issue to both instructors
- [x] Capture output of java -version and add it to `3_jv.md`

**Comment by mfernest** [comment]
See commit [da4018e](https://github.com/Mladen-Trampic-SRB-1989/SEBC/commit/da4018e01be89aa54521dee1014d64ed30f8ab72)
