### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by Mladen-Trampic-SRB-1989** [Mladen-Trampic-SRB-1989/SEBC#12]
- [x] Create the Issue `Test HDFS`
- [x] Assign the issue to yourself and label it `started`
- [x] As user `ernest`, use `teragen` to generate a 51,200,000-record dataset into six files
    - [x] Set the block size to 32 MB
    - [x] Name the target directory `tgen512m`
    - [x] Use the `time` command to capture job duration
- [x] Put the following in the file `challenges/labs/4_teragen.md`
    - [x] The full `teragen` command 
    - [x] The output of the `time` command
    - [x] The command and output of `hdfs dfs -ls /user/ernest/tgen512m`
    - [x] Show how many blocks are associated with this directory
- [x] Push this work to your GitHub repo and label the Issue `submitted`
- [x] Assign the issue to both instructors

**Comment by mfernest** [comment]
See commit [69b8edc](https://github.com/Mladen-Trampic-SRB-1989/SEBC/commit/69b8edc631ba186cdce86be1b81e8006edc50da7)
